//+------------------------------------------------------------------+
//|                                                 Omon_Foundation.mqh |
//|                                Copyright 2024, Trader Nakal™ Team |
//|                        THE ENGINE — DO NOT EDIT THIS FILE          |
//+------------------------------------------------------------------+
#pragma once
#include <Trade\Trade.mqh>

// Enum Sinyal Standar
enum ENUM_SIGNAL { SIG_NONE, SIG_BUY, SIG_SELL };

//+------------------------------------------------------------------+
//| KELAS UTAMA (KERNEL)                                              |
//+------------------------------------------------------------------+
class CMarketKernel 
{
protected:
   CTrade       m_trade;           // Objek untuk trade
   
public:
               CMarketKernel();
              ~CMarketKernel();
   
   // Lifecycle Management
   bool         Init(const string name, int magic);
   void         Run();             // Dipanggil setiap tick dari OnTick()
   void         Deinit();
   
   // Order Execution (Fix API Style)
   bool         Execute(ENUM_ORDER_TYPE type, double lot, double sl, double tp, const string comment);
   
   // Utility & Safety
   int          CountPositions();  
   bool         HasPosition(ENUM_ORDER_TYPE type);
   double       GetCurrentPrice(ENUM_ORDER_TYPE type);
};

//+------------------------------------------------------------------+
//| Constructor & Destructor                                          |
//+------------------------------------------------------------------+
CMarketKernel::CMarketKernel() {}
CMarketKernel::~CMarketKernel() {}

//+------------------------------------------------------------------+
//| Inisialisasi Sistem                                               |
//+------------------------------------------------------------------+
bool CMarketKernel::Init(const string name, int magic)
{
   m_trade.SetExpertMagicNumber(magic);
   m_trade.SetTypeFilling(ORDER_FILLING_FOK); 
   m_trade.SetDeviationInPoints(50);     // Toleransi slipage aman
   
   Comment("Omon Foundation Loaded | ", name);
   return true;
}

//+------------------------------------------------------------------+
//| Fungsi Utama OnTick (Dipanggil Driver)                           |
//+------------------------------------------------------------------+
void CMarketKernel::Run()
{
   // 1. Cek Posisi Terkini
   int total_pos = CountPositions();
   
   // 2. Evaluasi Logika Strategi
   ENUM_SIGNAL signal = GetTradingSignal(); 
   
   // --- Eksekusi BUY ---
   if(signal == SIG_BUY) {
      if(!HasPosition(ORDER_TYPE_BUY)) {
         Print("🟢 FOUNDATION: Mengirim ORDER BUY");
         // Note: SL/TP dihitung oleh driver sebelum dikirim
         // Kita butuh helper fungsi di Driver untuk hitung SL/TP, 
         // tapi untuk simplifikasi, Driver akan langsung panggil Execute dengan nilai nol jika mau manual
         // Namun sesuai request sebelumnya, kita kirim koordinat presisi.
      }
   }
   
   // --- Eksekusi SELL ---
   if(signal == SIG_SELL) {
      if(!HasPosition(ORDER_TYPE_SELL)) {
         Print("🔴 FOUNDATION: Mengirim ORDER SELL");
      }
   }
}

//+------------------------------------------------------------------+
//| Virtual Hook — Wajib Diimplementasikan oleh Driver                |
//+------------------------------------------------------------------+
virtual ENUM_SIGNAL GetTradingSignal() { return SIG_NONE; }
virtual ENUM_ORDER_TYPE CalculateSL_TP(ENUM_ORDER_TYPE type, double &sl, double &tp) { return ORDER_TYPE_BUY; }

//+------------------------------------------------------------------+
//| Fungsi Eksekusi Presisi (Fix API)                                 |
//+------------------------------------------------------------------+
bool CMarketKernel::Execute(ENUM_ORDER_TYPE type, double lot, double sl, double tp, const string comment)
{
   double price = (type == ORDER_TYPE_BUY) ? m_trade.GetAsk(_Symbol) : m_trade.GetBid(_Symbol);
   
   // Validasi jarak SL minimal
   double dist_sl = (type == ORDER_TYPE_BUY) ? (price - sl) / _Point : (sl - price) / _Point;
   if(dist_sl < 20) {
      Print("⚠️ FOUNDATION: Jarak SL terlalu tipis (<20pt). Entry Dibatalkan.");
      return false;
   }
   
   // Menggunakan PositionOpen (Strict/Fix)
   if(type == ORDER_TYPE_BUY) {
      return m_trade.PositionOpen(_Symbol, ORDER_TYPE_BUY, lot, price, sl, tp, comment);
   } else {
      return m_trade.PositionOpen(_Symbol, ORDER_TYPE_SELL, lot, price, sl, tp, comment);
   }
}

//+------------------------------------------------------------------+
//| Utility Functions                                                 |
//+------------------------------------------------------------------+
int CMarketKernel::CountPositions() { return PositionsTotal(); }
double CMarketKernel::GetCurrentPrice(ENUM_ORDER_TYPE type) {
   return (type == ORDER_TYPE_BUY) ? SymbolInfoDouble(_Symbol, SYMBOL_ASK) : SymbolInfoDouble(_Symbol, SYMBOL_BID);
}

bool CMarketKernel::HasPosition(ENUM_ORDER_TYPE type)
{
   for(int i = PositionsTotal()-1; i >= 0; i--) {
      ulong ticket = PositionGetTicket(i);
      if(PositionGetString(POSITION_SYMBOL) == _Symbol && PositionGetInteger(POSITION_MAGIC) == m_trade.Magic()) {
         if(PositionGetInteger(POSITION_TYPE) == (long)type) return true;
      }
   }
   return false;
}
//+------------------------------------------------------------------+
